### ISSUE TITLE
💄 (Website) Footer is covering the bottom part of Results and Home tabs

### ISSUE THREAD

**Issue by mvantubbergh** [COS301-SE-2022/Vote-Vault#111]
This is likely due to the CSS property **display** or **position**

**Comment by RainbowPeanut69** [comment]
We will look into that aswell

**Comment by RainbowPeanut69** [comment]
The homepage needs fixing but its not a problem in results when you scroll down all the way, i cant see anything wrong, could you see what the problem is?

**Comment by RainbowPeanut69** [comment]
We fixed the footer problem
