### ISSUE TITLE
💄  (Website) Fix homepage textbox

### ISSUE THREAD

**Issue by mvantubbergh** [COS301-SE-2022/Vote-Vault#91]
Remove the scrollbar from the information textbox on the homepage

**Comment by RainbowPeanut69** [comment]
Ill see what i can do

**Comment by RainbowPeanut69** [comment]
It seen to be fixed, is it still there?

**Comment by mvantubbergh** [comment]
> It seen to be fixed, is it still there?

Sorry I have fixed it in the meantime
